---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
```

# Their Model

```{r}
source("code/models/CHN_generate_data_and_model_projection.R")
```

# Compiling Actual Information

```{r}
cumulative_infections_counts <-
  china_data %>%
  group_by(date) %>%
  summarize(cum_infections = sum(cum_confirmed_cases, na.rm = T))
```

```{r}
head(cumulative_infections_counts)
```

```{r}
method_comparison <- inner_join(cumulative_infections_counts, main_projection, by = "date")
```

```{r}
method_comparison$dates_since <- as.integer(method_comparison$date - as.Date("2020-01-16"))
```

# Our Model

```{r}
logistic_curve_model <- nls(cum_infections ~ SSlogis(dates_since, Asym, xmid, scal), data = method_comparison)
coefs <- summary(logistic_curve_model)$coef
```

```{r}
c <- coefs[1]
a <- coefs[2]
k <- 1/coefs[3]

method_comparison$predicted_cum_confirmed_cases <- c/(1 + exp(-k*(method_comparison$dates_since - a)))
```

# Graphical Aids

```{r}
tf_cols <- c("cum_infections", "predicted_cum_confirmed_cases_true", "predicted_cum_confirmed_cases_no_policy")

log_method_comparison <- method_comparison
log_method_comparison[tf_cols] <- log(log_method_comparison[tf_cols])
```

```{r}
method_comparison <- select(method_comparison, date, dates_since, real_count = cum_infections, parent_pred = predicted_cum_confirmed_cases_true, student_pred = predicted_cum_confirmed_cases)

head(method_comparison)
```


# Result

```{r}
# comparing actual predictions of cumulative infections
# black line = true
# red line = their prediction
# blue line = our prediction
ggplot(data = method_comparison, aes(x = date)) +
  geom_line(aes(y = real_count), color = "black") +
  geom_line(aes(y = parent_pred), color = "red") +
  geom_line(aes(y = student_pred), color = "blue")
```

